services:
  postgres:
    container_name: stage_postgres
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stage_database