version: '3.8'
services:
  db:
    image: postgres
    container_name: stage_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stage_database
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stage_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stage_database
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    # Aqui o comando de inicialização (que utiliza a conexão com o DB) é executado em runtime
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:+UseSerialGC", "-XX:MaxMetaspaceSize=128m", "-jar", "app.jar"]


networks:
  app-network:
    driver: bridge